# Generated by Django 4.2 on 2023-04-11 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='descr',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='descr',
            new_name='description',
        ),
    ]
